<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your PIN_form-control pincode-i_c9f094</name>
   <tag></tag>
   <elementGuidId>7978b8aa-6ff5-4475-a4e2-cda6a8f835e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pin-auth-loader-wrapper > div.pin-input-wrapper > div.pincode-input-container > input.form-control.pincode-input-text.pincode-input-text-masked.first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f13d485-6959-447c-ada0-c4652064fda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b29fcc43-6466-4c44-a3d0-401e6bc7a3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>88fe39a4-0044-4eaf-a743-4061d6cdafe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3f88d9e5-9447-4590-baf9-58c7612ead0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pincode-input-text pincode-input-text-masked first</value>
      <webElementGuid>887ccffc-8722-4d21-a6ae-49629ba60118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-auth&quot;)/div[@class=&quot;pin-auth-loader-wrapper&quot;]/div[@class=&quot;pin-input-wrapper&quot;]/div[@class=&quot;pincode-input-container&quot;]/input[@class=&quot;form-control pincode-input-text pincode-input-text-masked first&quot;]</value>
      <webElementGuid>c99d4bc0-e703-4fea-a510-744a8eb0180e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[12]</value>
      <webElementGuid>d6484739-37ad-4e46-87bd-f9bfda0e858b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pin-auth']/div/div/div/input</value>
      <webElementGuid>61c50b01-e93b-4487-99c7-c8f307e4837d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>9e645e0a-0ba6-4556-a626-f9e18560791f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>f46ae4a3-0bd1-4c65-9b0b-b9f4736afce3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
