<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Car Park Ratio 1729 SF</name>
   <tag></tag>
   <elementGuidId>3182b8e3-4ffa-4849-b45d-4dd16ee5a40a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1']/div/div[2]/div[2]/div/ul/li[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>bec20e8f-809f-4f83-9c53-8eb78f7ff0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Car Park Ratio: 1:729 SF
                                            </value>
      <webElementGuid>5fc3ccd0-7446-4a82-9a15-d046483979b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/div[@class=&quot;overview-wapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;overview-options&quot;]/ul[1]/li[6]</value>
      <webElementGuid>5f35d8f0-b481-4c6b-ad61-dc6d4d1a4417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div[2]/div[2]/div/ul/li[6]</value>
      <webElementGuid>0aefecc8-221d-463c-9eb8-e7901b64d7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Parks:'])[1]/following::li[1]</value>
      <webElementGuid>e65de38b-74da-4414-bc4d-0e5ed3879353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area:'])[1]/following::li[2]</value>
      <webElementGuid>d95ca510-15ef-4dad-b014-3fbd38eda63e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Investment Update'])[1]/preceding::li[1]</value>
      <webElementGuid>9998185c-5a99-4617-811a-8c5abfbe1488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1:729 SF']/parent::*</value>
      <webElementGuid>fad40863-9c63-4f3d-9b59-1cbfe51515ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li[6]</value>
      <webElementGuid>be5e2888-f5c9-4d25-944f-cf836c573609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Car Park Ratio: 1:729 SF
                                            ' or . = 'Car Park Ratio: 1:729 SF
                                            ')]</value>
      <webElementGuid>5296ce03-910f-4953-a749-0223e93fc310</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
