<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Car Parks 44</name>
   <tag></tag>
   <elementGuidId>741c8a94-a689-4e71-9222-ec46e52a26b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1']/div/div[2]/div[2]/div/ul/li[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>914c5f58-fda7-46fb-8ee8-4dde50576957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Car Parks: 44
                                            </value>
      <webElementGuid>4f897dfb-672d-45eb-a6ef-c97b60878ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/div[@class=&quot;overview-wapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;overview-options&quot;]/ul[1]/li[5]</value>
      <webElementGuid>99429232-597d-49b5-a404-45905b8f0e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div[2]/div[2]/div/ul/li[5]</value>
      <webElementGuid>18d47880-2623-4fc7-812c-cf21146c0288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area:'])[1]/following::li[1]</value>
      <webElementGuid>1fd951ff-b013-42a3-a1e5-a938d3d6288a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tenant:'])[1]/following::li[2]</value>
      <webElementGuid>b214c0fb-33df-42d3-af9e-7118924a78e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Car Park Ratio:'])[1]/preceding::li[1]</value>
      <webElementGuid>530f911d-9b93-49f5-ab92-43aadebdd186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='44']/parent::*</value>
      <webElementGuid>98232859-c940-43c5-bc84-a2bf112b44e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li[5]</value>
      <webElementGuid>0a0cba7f-fa10-426f-a60c-ff485da0800c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Car Parks: 44
                                            ' or . = 'Car Parks: 44
                                            ')]</value>
      <webElementGuid>dfeeefc1-8c08-41e7-993d-dfefc9bf3fc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
