<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Date of Investment Sep 2019</name>
   <tag></tag>
   <elementGuidId>a32cf11e-5606-4b68-a363-9d8981a7237f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.overview-options > ul > li</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab1']/div/div[2]/div[2]/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>651cab1d-0f4f-417c-a1ec-f88c3ca5a22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Date of Investment: Sep 2019</value>
      <webElementGuid>3f6c4433-3cea-420f-81d9-865db5b3f39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/div[@class=&quot;overview-wapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/div[@class=&quot;overview-options&quot;]/ul[1]/li[1]</value>
      <webElementGuid>956314bc-9d4f-43a3-8189-e136eceb3998</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab1']/div/div[2]/div[2]/div/ul/li</value>
      <webElementGuid>247af672-3fda-4ff3-8515-3ebff1762553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='location'])[1]/following::li[1]</value>
      <webElementGuid>d49977f6-ced8-49e5-bae1-9a65588c3dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='view floor plan'])[1]/following::li[2]</value>
      <webElementGuid>8aab8629-74fe-41ab-8ae2-063a5864eb52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purchase Price:'])[1]/preceding::li[1]</value>
      <webElementGuid>9e2c9949-3099-4ba5-bc6c-ab9f3b504660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sep 2019']/parent::*</value>
      <webElementGuid>575f61af-2e71-48c0-bb53-f1695217e4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/ul/li</value>
      <webElementGuid>6f1b1d15-638d-41e1-a615-82c200776cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'Date of Investment: Sep 2019' or . = 'Date of Investment: Sep 2019')]</value>
      <webElementGuid>149d453a-b3d5-4140-9416-a0c6d27f2e52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
