<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your PIN_form-control pincode-i_c9f094</name>
   <tag></tag>
   <elementGuidId>65e61cb0-66f7-4bf0-bbfd-f5f76c9a62e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[12]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.pin-auth-loader-wrapper > div.pin-input-wrapper > div.pincode-input-container > input.form-control.pincode-input-text.pincode-input-text-masked.first</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>424dd289-6baa-4bf6-adf8-40ebb8be018e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ebd2a7d-a112-4fb5-8bb7-27e303a70185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>131fcb52-5886-44f5-89cd-6308cda27f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c3fc0021-ea04-4ccb-8c9d-a0edeef06cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pincode-input-text pincode-input-text-masked first</value>
      <webElementGuid>ffa971aa-d0b3-405b-8df9-dc146567bb59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-auth&quot;)/div[@class=&quot;pin-auth-loader-wrapper&quot;]/div[@class=&quot;pin-input-wrapper&quot;]/div[@class=&quot;pincode-input-container&quot;]/input[@class=&quot;form-control pincode-input-text pincode-input-text-masked first&quot;]</value>
      <webElementGuid>c9ad4898-2c4d-4059-b89e-5c8b1fd290b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[12]</value>
      <webElementGuid>bd2e0898-0c54-49c8-90a6-25d4bb3d024e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pin-auth']/div/div/div/input</value>
      <webElementGuid>a02a7dbd-f011-44aa-80bb-aad809f8992d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>0d117b0e-58a6-4889-89f5-f1889bdda719</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>7369c278-543c-4426-b263-8dce5dc52dc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
