<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_PMS</name>
   <tag></tag>
   <elementGuidId>282a3a13-4503-4303-8fbc-3c61ca08e9a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pms-complaints</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='pms-complaints']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>35042318-02b8-42d7-b504-50fcb80d37ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link</value>
      <webElementGuid>b5d62891-0b93-4ae1-90f2-cb769e4f987d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pms-complaints</value>
      <webElementGuid>20e9ff40-88e9-4b82-977f-bc3090cec457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>253b2434-fa15-4e7f-8967-82fb08408530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#pms-complaints-tab</value>
      <webElementGuid>fc4643dc-1f59-40e7-9c0b-7c613fb5938b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>122120ba-d1ba-469d-86d6-3ab0b469d503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>pms-complaints</value>
      <webElementGuid>1b080ddc-bc20-4a7c-948c-19a44e09ab48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6cd290a7-f9fb-4c89-a2a6-01f511bfc1bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tabtype</name>
      <type>Main</type>
      <value>pms-complaints-data</value>
      <webElementGuid>aa1a6aed-1f9c-420d-b795-aa22cdca5eab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PMS</value>
      <webElementGuid>5df4079f-4951-41b4-b1bb-fe3de24e26ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pms-complaints&quot;)</value>
      <webElementGuid>776ff3ba-1542-466e-8251-376984b4efbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='pms-complaints']</value>
      <webElementGuid>f0125d65-2cf8-4dd7-8148-b157d2b84f44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'PMS')]</value>
      <webElementGuid>43e235c6-c46c-4f4f-a95e-5c7fa89e8f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IA'])[1]/following::a[1]</value>
      <webElementGuid>593a4cfd-8de8-4031-82cd-171a2167bf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Opportunities'])[1]/following::a[2]</value>
      <webElementGuid>9e823bfe-40e3-4d84-84d0-2349b1ef5ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending at the end of last month'])[1]/preceding::a[4]</value>
      <webElementGuid>638f3af9-5dab-4a4e-b65a-644dcf0ac776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Received during the month'])[1]/preceding::a[4]</value>
      <webElementGuid>48d435a8-e154-443e-840c-3f42112ff420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PMS']/parent::*</value>
      <webElementGuid>272f1887-03da-44bb-9989-3c76c62a52aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#pms-complaints-tab')]</value>
      <webElementGuid>4b92fc3e-7c67-4178-aa6d-208612b57715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/ul/li[2]/a</value>
      <webElementGuid>1c4d2fa0-cb94-4fa3-b1c5-a9db7c18d6ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'pms-complaints' and @href = '#pms-complaints-tab' and (text() = 'PMS' or . = 'PMS')]</value>
      <webElementGuid>b32a697a-0035-4b7f-bfbb-e18a09b4411c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
