<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your PIN_form-control pincode-i_c9f094</name>
   <tag></tag>
   <elementGuidId>633c611b-d7e0-4283-b85a-7a4440a04541</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pin-auth-loader-wrapper > div.pin-input-wrapper > div.pincode-input-container > input.form-control.pincode-input-text.pincode-input-text-masked.first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[13]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>545f3cf8-45ef-4c93-a304-fc19aba3400e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6069b99-ca13-451d-9cde-1af47bb3f4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>47f4f26b-1203-403f-af87-0cce2cccdbed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b0c2c33d-8d91-4449-896e-66524314b2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pincode-input-text pincode-input-text-masked first</value>
      <webElementGuid>6bf89077-69a8-46fa-92d5-3fa2232a1ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-auth&quot;)/div[@class=&quot;pin-auth-loader-wrapper&quot;]/div[@class=&quot;pin-input-wrapper&quot;]/div[@class=&quot;pincode-input-container&quot;]/input[@class=&quot;form-control pincode-input-text pincode-input-text-masked first&quot;]</value>
      <webElementGuid>9ac43bf7-bfa2-43ae-9410-4857ae74f1ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[13]</value>
      <webElementGuid>e17776a1-9a41-4c5a-aeec-014603f9283b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pin-auth']/div/div/div/input</value>
      <webElementGuid>06ccf808-46c9-4f81-9ad4-068cb3bdb49d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>085cf70f-368c-4542-bc3f-989ce14a605d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>cf3113a9-c2bc-402e-a9da-27f4ef900115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
