<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your PIN_form-control pincode-i_c9f094</name>
   <tag></tag>
   <elementGuidId>f60afaac-1ad0-4ad2-b646-b78d7731f013</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pin-auth-loader-wrapper > div.pin-input-wrapper > div.pincode-input-container > input.form-control.pincode-input-text.pincode-input-text-masked.first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98a25628-278a-40e2-8a9d-a4feb5244e53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>499e2778-5474-4862-a085-7d26deac8f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0d37011e-8b94-44b8-a419-4b5ba50dfb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>84bf7d25-50fb-4acc-98ec-6fa3ba5533e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pincode-input-text pincode-input-text-masked first</value>
      <webElementGuid>1b855687-0f1f-4dea-a8b0-b839aa3e78e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-auth&quot;)/div[@class=&quot;pin-auth-loader-wrapper&quot;]/div[@class=&quot;pin-input-wrapper&quot;]/div[@class=&quot;pincode-input-container&quot;]/input[@class=&quot;form-control pincode-input-text pincode-input-text-masked first&quot;]</value>
      <webElementGuid>e6fef2ae-ec46-4597-bfb3-c5e946916f36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[12]</value>
      <webElementGuid>7d37e2e8-6f34-4971-9b76-19b18b01c6e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pin-auth']/div/div/div/input</value>
      <webElementGuid>e9362532-ce2c-4445-a8b0-879f44d0d1d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>07e8640e-e1e7-4b25-a7e2-ab975930ce77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>bf269940-5af4-4201-95b0-fcef8ccfd8aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
