<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_pricing</name>
   <tag></tag>
   <elementGuidId>bd44b597-dc96-443a-8056-e2f8e673d94a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='IBC Knowledge Park'])[1]/following::p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>57896b13-e0d2-4dfd-b431-3a7ff67d7bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pricing</value>
      <webElementGuid>ba31a2fc-2de3-492a-97d0-323a349443dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row zero-margin-row-container&quot;]/div[@class=&quot;col-md-10 offset-md-1 offset-sm-0 col-sm-12 col-12 offset-0 no-padding&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row zero-margin-row-container&quot;]/div[@class=&quot;col-md-10 offset-md-1 col-12  overview_content no-padding investment_myproperties investment_myproperties_hidden&quot;]/div[@class=&quot;size-restriction&quot;]/div[@class=&quot;investment_tab_list&quot;]/div[@class=&quot;row property_details&quot;]/div[@class=&quot;col-sm-12 property_indi_details&quot;]/div[@class=&quot;property-detials-tabs&quot;]/ul[@class=&quot;property_list_details&quot;]/li[2]/a[1]/div[@class=&quot;options&quot;]/p[1]</value>
      <webElementGuid>3ed00142-c97a-45a2-9ad1-ff6cd97e4f7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IBC Knowledge Park'])[1]/following::p[2]</value>
      <webElementGuid>8f0b8bd1-8fd5-45fb-a6c9-f4999c1e9f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Dashboard'])[1]/following::p[2]</value>
      <webElementGuid>28312570-502d-45dd-80f0-ead0b7f5fc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='view floor plan'])[1]/preceding::p[14]</value>
      <webElementGuid>599dc268-0bfe-4dba-89f4-df293e440917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='location'])[1]/preceding::p[14]</value>
      <webElementGuid>c13457e5-2954-43cf-9d2f-9fa6b34bd819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='pricing']/parent::*</value>
      <webElementGuid>ebf6ebe5-c60f-41c4-bf7d-8aaeed2a9990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/p</value>
      <webElementGuid>4d876bef-8b36-48ac-8838-7fb80743dfd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'pricing' or . = 'pricing')]</value>
      <webElementGuid>c7136286-78ce-467c-8b36-3f90755aaec6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
