<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter your PIN_form-control pincode-i_c9f094</name>
   <tag></tag>
   <elementGuidId>64379949-044c-4487-93f1-60d9ad573369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pin-auth-loader-wrapper > div.pin-input-wrapper > div.pincode-input-container > input.form-control.pincode-input-text.pincode-input-text-masked.first</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@type='text'])[12]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91e51752-7595-4a0b-afea-c096ca569297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f016adb-f797-4ab4-9f72-cbc9cf0b5704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d94d7d33-5f0e-430b-86b7-05f5a11e9e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3a37e6b5-4d1e-4fe7-9fc0-a61a692f5a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control pincode-input-text pincode-input-text-masked first</value>
      <webElementGuid>c2b795c6-c475-4896-a349-47b04a57b729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pin-auth&quot;)/div[@class=&quot;pin-auth-loader-wrapper&quot;]/div[@class=&quot;pin-input-wrapper&quot;]/div[@class=&quot;pincode-input-container&quot;]/input[@class=&quot;form-control pincode-input-text pincode-input-text-masked first&quot;]</value>
      <webElementGuid>0fa7d10b-c9bd-4758-9da0-6c91299e2893</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@type='text'])[12]</value>
      <webElementGuid>a694d998-3757-42d7-99e2-faadec6cbea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='pin-auth']/div/div/div/input</value>
      <webElementGuid>a8529d82-f5ea-49b6-bb57-ce1c44cb236a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/form/div/div/div/input</value>
      <webElementGuid>922c3914-881f-406a-8935-215cb5cfc4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>115b17cf-e549-46e2-9cca-41f83f751080</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
