<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign In                             _8f69dc</name>
   <tag></tag>
   <elementGuidId>c406c716-b9bb-4f0a-a388-557cf1f48dad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#propshare-login-form-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='propshare-login-form-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a966a2ec-7981-4c69-bf54-f1f93196b062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>de050af6-fce5-4c3e-9f37-f653522d9b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>propshare-login-form-btn</value>
      <webElementGuid>e1f1b1b4-658c-4682-b90b-d59ac303803f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary propshare-login-btn</value>
      <webElementGuid>061baa68-bcab-40a0-8b13-0648429caa71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                Sign In
                                Loading...
                            </value>
      <webElementGuid>268e71d3-0878-46c3-9b14-4cdc56056eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;propshare-login-form-btn&quot;)</value>
      <webElementGuid>c5bb8c5a-d2c1-4c8a-a9d9-3f5f6218f25b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='propshare-login-form-btn']</value>
      <webElementGuid>3e7d863b-2fc5-4eda-9a7b-056239140f33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='propshare-login-form']/div[4]/button</value>
      <webElementGuid>37f83595-dafd-4465-bd49-eac821e3761a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/following::button[1]</value>
      <webElementGuid>f4cbf207-e751-42d3-9d14-d2d142fb66de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::button[1]</value>
      <webElementGuid>226c1dd1-4c81-4047-a845-e99922eca870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>31f3cf5a-58a3-464a-bc25-a5c1ee4d5484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'propshare-login-form-btn' and (text() = '
                                Sign In
                                Loading...
                            ' or . = '
                                Sign In
                                Loading...
                            ')]</value>
      <webElementGuid>c15dbae0-d679-40f6-8146-61cde53f1fb4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
