<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Our Investors Are Our Partners_img-wrap_0cf8cf</name>
   <tag></tag>
   <elementGuidId>1a24fa0d-37ca-4ccc-881f-5e343b514214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.img-wrapper.google-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='slick-slide10']/div/div/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e14d7902-3745-4011-a6c2-c39d0af95e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-wrapper google-block</value>
      <webElementGuid>c08cf15c-8bb6-40d4-8e0c-ebaa2b455f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;slick-slide10&quot;)/div[1]/div[@class=&quot;investor-work-location-list&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;company&quot;]/div[@class=&quot;img-wrapper google-block&quot;]</value>
      <webElementGuid>3c949765-f7f3-4922-96a0-0966d525a334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slick-slide10']/div/div/div/div/div/div</value>
      <webElementGuid>e27545ca-d278-4cb8-8b7b-fa7c72aa1cad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div/div</value>
      <webElementGuid>7c554b13-032c-4a82-86ff-537bb02b31df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
