<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>304ae3a1-e90b-4e1b-9d5d-96bbe92c892f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Investor Map wrapper&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='Investor Map wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c894cd24-a703-4807-bfd3-0e018217208b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://staging.propsharecapital.com/images/aif/map_white.png</value>
      <webElementGuid>08b7ef7b-6271-49a8-bfce-c60827d24fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Investor Map wrapper</value>
      <webElementGuid>93396812-1e35-4d18-8ede-38433cfc3572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;ps-section-wrapper&quot;]/div[@class=&quot;container&quot;]/section[1]/div[@class=&quot;section-body-wrapper&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;map-image-wrapper&quot;]/img[1]</value>
      <webElementGuid>4fc97df5-7e02-4d48-a433-8416595009ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Investor Map wrapper']</value>
      <webElementGuid>c0649dc3-e186-4587-baa4-3b1272f514a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>2f7d4544-0b35-435a-a665-f4f3c7e2ee9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://staging.propsharecapital.com/images/aif/map_white.png' and @alt = 'Investor Map wrapper']</value>
      <webElementGuid>a91aba53-2756-4056-aecb-53158d5cff22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
