<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_investpropsharecapital.com</name>
   <tag></tag>
   <elementGuidId>4abccd5b-9487-47be-bb23-adab485b7c2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ps-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-us']/div/section/div[2]/div/div[3]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>38654340-03e1-423e-bc8c-cb6c0e425619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-link</value>
      <webElementGuid>e8a0517b-08e1-42b6-be41-db71c936b3fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:invest@propsharecapital.com</value>
      <webElementGuid>019fd592-a873-4508-9380-bb8404d9f496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>invest@propsharecapital.com</value>
      <webElementGuid>d947b203-636e-4016-a248-b5d0b0fa0d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-us&quot;)/div[@class=&quot;container&quot;]/section[1]/div[@class=&quot;section-body-wrapper&quot;]/div[@class=&quot;row contact-us-description-wrapper&quot;]/div[@class=&quot;col-md-4 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;contact-info-block&quot;]/div[@class=&quot;contact-description&quot;]/a[@class=&quot;ps-link&quot;]</value>
      <webElementGuid>dc358c77-3f42-4282-bc20-12c7887167dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-us']/div/section/div[2]/div/div[3]/div/div/div[2]/a</value>
      <webElementGuid>a3d0c96b-4cc7-4d48-b482-88a988e3886d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'invest@propsharecapital.com')]</value>
      <webElementGuid>583e9162-2349-4d9a-a7d0-a049034fb366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kasturba Road, Bangalore 560001'])[1]/following::a[1]</value>
      <webElementGuid>396f3b96-130d-4bc6-b7de-875837614444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::a[1]</value>
      <webElementGuid>cee59bc4-85cc-466a-b093-a0368245e94d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become an Investor'])[4]/preceding::a[1]</value>
      <webElementGuid>3f0cc4e7-2fb3-46bf-9ec1-aacf3381b9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::a[2]</value>
      <webElementGuid>520c347d-7f63-4043-b00a-ad801720f4ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='invest@propsharecapital.com']/parent::*</value>
      <webElementGuid>05398498-bb13-4521-a743-2e7679d8e328</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:invest@propsharecapital.com')]</value>
      <webElementGuid>0eacc492-935d-4acd-b4a9-2b27ccf7bc99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/a</value>
      <webElementGuid>a633f555-75ed-4463-a1ae-d70340672b48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:invest@propsharecapital.com' and (text() = 'invest@propsharecapital.com' or . = 'invest@propsharecapital.com')]</value>
      <webElementGuid>6a61cb2e-23d0-42e4-9318-abef2ac82c1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
