<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_investpropsharecapital.com</name>
   <tag></tag>
   <elementGuidId>8cc0d857-0987-49dd-8c79-5808260c8420</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.ps-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-us']/div/section/div[2]/div/div[3]/div/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4ff5f6c8-a1da-473c-920c-a048f41746f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-link</value>
      <webElementGuid>5db43138-e13d-4cc3-9a14-0fd364f763d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:invest@propsharecapital.com</value>
      <webElementGuid>26764283-a0e0-40de-82c4-1ca370e10d9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>invest@propsharecapital.com</value>
      <webElementGuid>10f8252d-bac7-450f-a4eb-8112b88301c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-us&quot;)/div[@class=&quot;container&quot;]/section[1]/div[@class=&quot;section-body-wrapper&quot;]/div[@class=&quot;row contact-us-description-wrapper&quot;]/div[@class=&quot;col-md-4 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;contact-info-block&quot;]/div[@class=&quot;contact-description&quot;]/a[@class=&quot;ps-link&quot;]</value>
      <webElementGuid>d7a460bb-57b5-4713-b6f8-2d4620299fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-us']/div/section/div[2]/div/div[3]/div/div/div[2]/a</value>
      <webElementGuid>21978954-bb41-4ca9-a417-8da600186470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'invest@propsharecapital.com')]</value>
      <webElementGuid>a230e64e-1346-41b7-ad56-2fd49536e837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kasturba Road, Bangalore 560001'])[1]/following::a[1]</value>
      <webElementGuid>7c91767f-7435-46ba-b692-714a2157b68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::a[1]</value>
      <webElementGuid>c56dd5c9-5c77-4c11-9dca-691e7da3a1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become an Investor'])[4]/preceding::a[1]</value>
      <webElementGuid>5296e7d5-e28f-4411-8792-ff71df76bda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::a[2]</value>
      <webElementGuid>a088a239-81d5-48fe-84ea-cd74bf467638</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='invest@propsharecapital.com']/parent::*</value>
      <webElementGuid>7f3fbf6f-26d5-4455-b916-282fd798daca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:invest@propsharecapital.com')]</value>
      <webElementGuid>185089e5-e4a0-46ab-9191-b6be52ec6b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[2]/a</value>
      <webElementGuid>6ae0f850-5daa-4074-a341-3f5192d7d16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:invest@propsharecapital.com' and (text() = 'invest@propsharecapital.com' or . = 'invest@propsharecapital.com')]</value>
      <webElementGuid>f7569682-8930-4689-b97e-5de29fda63ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
