<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_91-95-1376-1376</name>
   <tag></tag>
   <elementGuidId>604e6241-c64b-4d05-a625-1e584a10a1bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contact-us']/div/section/div[2]/div/div[2]/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7d3f7d1b-41fc-4ea9-9a01-f0164360f7cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>contact-description</value>
      <webElementGuid>89c44f70-2110-4b2e-b769-70a1a39684db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            +91-95-1376-1376
                                        </value>
      <webElementGuid>f20a517b-d262-4d90-b513-4af364800948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact-us&quot;)/div[@class=&quot;container&quot;]/section[1]/div[@class=&quot;section-body-wrapper&quot;]/div[@class=&quot;row contact-us-description-wrapper&quot;]/div[@class=&quot;col-md-4 col-12&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;contact-info-block&quot;]/div[@class=&quot;contact-description&quot;]</value>
      <webElementGuid>0e062e7b-2c45-4ba8-89f0-5761df668b57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contact-us']/div/section/div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>efbd24d8-a58c-4217-a88a-c5c5930cfbed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kasturba Road, Bangalore 560001'])[1]/following::div[5]</value>
      <webElementGuid>ebdeaca8-5cf0-446d-adcd-849d8081c56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[2]/following::div[13]</value>
      <webElementGuid>0c56e1fb-edbd-4199-9a39-2e92cb4e03dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='invest@propsharecapital.com'])[1]/preceding::div[2]</value>
      <webElementGuid>8c77e1cc-7378-4471-a5fa-60acd918b014</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Become an Investor'])[4]/preceding::div[46]</value>
      <webElementGuid>865f774f-deff-4c03-9763-de2cd807e698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+91-95-1376-1376']/parent::*</value>
      <webElementGuid>40d2854a-82d1-48b3-97c8-4acd3cca9484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/div[2]</value>
      <webElementGuid>c9bb8735-78ac-4fc9-b395-accc572e7bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                            +91-95-1376-1376
                                        ' or . = '
                                            +91-95-1376-1376
                                        ')]</value>
      <webElementGuid>1b8269fe-34ab-4851-8326-729bd589d481</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
